# Generated by Django 6.0.1 on 2026-03-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="fund",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entity",
                to="app_entity.fund",
            ),
        ),
    ]
