# Generated by Django 6.0.4 on 2026-04-20 21:35

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialCategoriesEntitiesRelations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "max_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_categories_entities_relations",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Financial Categories Entities Relations",
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="FinancialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category_type",
                    models.CharField(default="EXPENSE", editable=False, max_length=10),
                ),
                ("aspect", models.CharField(max_length=100)),
                (
                    "entity",
                    models.ManyToManyField(
                        related_name="categories",
                        through="app_entity.FinancialCategoriesEntitiesRelations",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Financial Categories",
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="financialcategoriesentitiesrelations",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities_relations",
                to="app_entity.financialcategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="financialcategoriesentitiesrelations",
            unique_together={("entity", "category")},
        ),
    ]
