# Generated by Django 6.0.1 on 2026-04-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="can_pay",
        ),
        migrations.AddField(
            model_name="fund",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
