# Generated by Django 6.0.1 on 2026-04-15 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0002_remove_entity_can_pay_fund_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactinfo",
            options={
                "verbose_name": "contact info",
                "verbose_name_plural": "contact info",
            },
        ),
        migrations.AlterModelOptions(
            name="entity",
            options={"verbose_name": "entity", "verbose_name_plural": "entities"},
        ),
        migrations.AlterModelOptions(
            name="fund",
            options={"verbose_name": "fund", "verbose_name_plural": "funds"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "person", "verbose_name_plural": "people"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "project", "verbose_name_plural": "projects"},
        ),
        migrations.AlterModelOptions(
            name="stakeholder",
            options={
                "verbose_name": "stakeholder",
                "verbose_name_plural": "stakeholders",
            },
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("address", "Address"),
                    ("website", "Website"),
                ],
                max_length=20,
                verbose_name="contact type",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="app_entity.entity",
                verbose_name="entity",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="is primary"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="label",
            field=models.CharField(
                choices=[("work", "Work"), ("personal", "Personal"), ("home", "Home")],
                max_length=50,
                verbose_name="label",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="value",
            field=models.CharField(max_length=255, verbose_name="value"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="is_client",
            field=models.BooleanField(default=False, verbose_name="is client"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="is_internal",
            field=models.BooleanField(default=False, verbose_name="is internal"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="is_shareholder",
            field=models.BooleanField(default=False, verbose_name="is shareholder"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="is_system",
            field=models.BooleanField(default=False, verbose_name="is system"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="is_vendor",
            field=models.BooleanField(default=False, verbose_name="is vendor"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="is_worker",
            field=models.BooleanField(default=False, verbose_name="is worker"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="is_world",
            field=models.BooleanField(default=False, verbose_name="is world"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="person",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entity",
                to="app_entity.person",
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entity",
                to="app_entity.project",
                verbose_name="project",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entity",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="fund",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="fund",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="fund",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="entity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fund",
                to="app_entity.entity",
                verbose_name="entity",
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="person",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="person",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="private_description",
            field=models.TextField(blank=True, verbose_name="private description"),
        ),
        migrations.AlterField(
            model_name="person",
            name="private_name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="private name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="project",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                max_length=180,
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="feasibility_study",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="feasibility study"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stakeholders",
                to="app_entity.entity",
                verbose_name="parent",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="role",
            field=models.CharField(
                choices=[
                    ("worker", "Worker"),
                    ("client", "Client"),
                    ("vendor", "Vendor"),
                    ("shareholder", "Shareholder"),
                ],
                max_length=30,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="app_entity.entity",
                verbose_name="target",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
