# Generated by Django 6.0.1 on 2026-03-03 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0002_alter_entity_fund"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="fund",
        ),
        migrations.AddField(
            model_name="fund",
            name="entity",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fund",
                to="app_entity.entity",
            ),
            preserve_default=False,
        ),
    ]
