# Generated by Django 6.0.4 on 2026-04-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0002_financialcategoriesentitiesrelations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("person", "Person"),
                    ("project", "Project"),
                    ("system", "System"),
                    ("world", "World"),
                ],
                max_length=10,
                null=True,
                verbose_name="entity type",
            ),
        ),
    ]
