# Generated by Django 6.0.4 on 2026-04-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0003_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("person", "Person"),
                    ("project", "Project"),
                    ("system", "System"),
                    ("world", "World"),
                ],
                default=None,
                max_length=10,
                verbose_name="entity type",
            ),
            preserve_default=False,
        ),
    ]
