# Generated by Django 6.0.1 on 2026-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0003_alter_contactinfo_options_alter_entity_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="private_description",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="person",
            name="private_name",
        ),
        migrations.AddField(
            model_name="person",
            name="name",
            field=models.CharField(
                default="name", max_length=255, unique=True, verbose_name="name"
            ),
            preserve_default=False,
        ),
    ]
