# Generated by Django 6.0.1 on 2026-03-03 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0003_remove_entity_fund_fund_entity"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="category",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="deletable",
        ),
        migrations.RemoveField(
            model_name="category",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="category",
            name="parent_entity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_categories",
                to="app_entity.entity",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="max_limit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
