# Generated by Django 6.0.1 on 2026-03-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0005_alter_category_managers_category_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinfo",
            name="content",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="type",
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("address", "Address"),
                    ("website", "Website"),
                ],
                default="phone",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="label",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="value",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="app_entity.entity",
            ),
        ),
    ]
