# Generated by Django 6.0.1 on 2026-04-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0005_entity_flat_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="person",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="project",
        ),
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("person", "Person"),
                    ("project", "Project"),
                    ("system", "System"),
                    ("world", "World"),
                ],
                max_length=10,
                verbose_name="entity type",
            ),
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
