# Generated by Django 6.0.1 on 2026-03-03 12:44

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import apps.app_base.mixins


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_entity",
            "0006_remove_contactinfo_content_remove_contactinfo_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="stakeholders",
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="label",
            field=models.CharField(
                choices=[("work", "Work"), ("personal", "Personal"), ("home", "Home")],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Stakeholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("worker", "Worker"),
                            ("client", "Client"),
                            ("Vendor", "Vendor"),
                            ("shareholder", "Shareholder"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "person_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to="app_entity.entity",
                    ),
                ),
                (
                    "project_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholders",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.app_base.mixins.ImmutableMixin, models.Model),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
