# Generated by Django 6.0.1 on 2026-04-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0006_remove_entity_person_remove_entity_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fund",
            name="entity",
        ),
    ]
