# Generated by Django 6.0.1 on 2026-03-03 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_entity",
            "0007_remove_entity_stakeholders_alter_contactinfo_label_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="stakeholder",
            old_name="project_entity",
            new_name="parent",
        ),
        migrations.RenameField(
            model_name="stakeholder",
            old_name="person_entity",
            new_name="other",
        ),
    ]
