# Generated by Django 6.0.1 on 2026-04-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0007_remove_fund_entity"),
        ("app_transaction", "0009_alter_transaction_source_alter_transaction_target"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fund",
        ),
    ]
