# Generated by Django 6.0.1 on 2026-03-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0008_rename_project_entity_stakeholder_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stakeholder",
            name="other",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="app_entity.entity",
            ),
        ),
    ]
