# Generated by Django 6.0.1 on 2026-03-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0009_alter_stakeholder_other"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stakeholder",
            old_name="other",
            new_name="target",
        ),
    ]
