# Generated by Django 6.0.1 on 2026-03-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0010_rename_other_stakeholder_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stakeholder",
            name="role",
            field=models.CharField(
                choices=[
                    ("worker", "Worker"),
                    ("client", "Client"),
                    ("vendor", "Vendor"),
                    ("shareholder", "Shareholder"),
                ],
                max_length=30,
            ),
        ),
    ]
