# Generated by Django 6.0.1 on 2026-03-03 14:36

from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.db import migrations

from apps.app_entity.models import Entity, Person


def create_admin(_, __):
    User = get_user_model()
    admin_user, created = User.objects.get_or_create(
        username="admin",
        first_name="admin",
        last_name="admin",
        password=make_password("admin"),
        is_superuser=True,
        is_staff=True,
    )
    admin_person, created = Person.objects.get_or_create(private_name="admin")
    Entity.create(owner=admin_person, auth_user=admin_user, fund=None)


def create_external_world_fund(apps, schema_editor):
    """
    Ensures a global 'External World' fund exists to act as the
    source for all incoming personal deposits.
    """
    world, created = Entity.objects.get_or_create(is_world=True)
    world.get_fund()


def reverse_create_external_world_fund(apps, schema_editor): ...


def create_internal_system_fund(apps, schema_editor):
    """
    Ensures a global 'External World' fund exists to act as the
    source for all incoming personal deposits.
    """
    system, created = Entity.objects.get_or_create(is_system=True)
    system.get_fund()


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0011_alter_stakeholder_role"),
    ]

    operations = [
        # Pass the forward function and the backward function (or RunPython.noop if irreversible)
        migrations.RunPython(code=create_external_world_fund, reverse_code=None),
        migrations.RunPython(code=create_internal_system_fund, reverse_code=None),
        migrations.RunPython(code=create_admin, reverse_code=None),
    ]
