# Generated by Django 6.0.1 on 2026-03-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0012_auto_20260303_1436"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
