# Generated by Django 6.0.4 on 2026-04-20 17:57

import apps.app_base.mixins
import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_entity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_periods",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Period",
                "verbose_name_plural": "Financial Periods",
                "ordering": ["entity", "-start_date"],
            },
            bases=(apps.app_base.mixins.ImmutableMixin, models.Model),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("CASH_INJECTION", "Cash Injection"),
                            ("CASH_WITHDRAWAL", "Cash Withdrawal"),
                            ("PROJECT_FUNDING", "Project Funding"),
                            ("PROJECT_REFUND", "Project Refund"),
                            ("PROFIT_DISTRIBUTION", "Profit Distribution"),
                            ("LOSS_COVERAGE", "Loss Coverage"),
                            ("INTERNAL_TRANSFER", "Internal Transfer"),
                            ("LOAN", "Loan"),
                            ("PURCHASE", "Purchase"),
                            ("SALE", "Sale"),
                            ("EXPENSE", "EXPENSE"),
                            ("CAPITAL_GAIN", "CAPITAL_GAIN"),
                            ("CAPITAL_LOSS", "CAPITAL_LOSS"),
                            ("WORKER_ADVANCE", "WORKER_ADVANCE"),
                            ("CORRECTION_CREDIT", "Correction Credit"),
                            ("CORRECTION_DEBIT", "Correction Debit"),
                            ("BIRTH", "Birth"),
                            ("DEATH", "Death"),
                            ("CONSUMPTION", "Consumption"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("description", models.TextField(blank=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_incoming",
                        to="app_entity.entity",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_supervised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="app_operation.financialperiod",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_operations",
                        to="app_operation.financialperiod",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="app_operation.operation",
                        verbose_name="reversal of",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_outgoing",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation",
                "verbose_name_plural": "Operations",
                "ordering": ["-date", "-created_at"],
            },
            bases=(
                apps.app_base.mixins.ImmutableMixin,
                apps.app_base.mixins.AdjustableMixin,
                apps.app_base.mixins.AmountCleanMixin,
                apps.app_base.mixins.LinkedIssuanceTransactionMixin,
                apps.app_base.mixins.LinkedPaymentTransactionMixin,
                apps.app_base.mixins.LinkedRePaymentTransactionMixin,
                apps.app_base.mixins.OfficerMixin,
                apps.app_base.mixins.HasRelatedTransactions,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="BirthOperation",
            fields=[],
            options={
                "verbose_name": "Birth",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="CapitalGainOperation",
            fields=[],
            options={
                "verbose_name": "Capital Gain",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="CapitalLossOperation",
            fields=[],
            options={
                "verbose_name": "Capital Loss",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="CashInjectionOperation",
            fields=[],
            options={
                "verbose_name": "Cash Injection",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="CashWithdrawalOperation",
            fields=[],
            options={
                "verbose_name": "Cash Withdrawal",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="ConsumptionOperation",
            fields=[],
            options={
                "verbose_name": "Consumption",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="CorrectionCreditOperation",
            fields=[],
            options={
                "verbose_name": "Correction Credit",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="CorrectionDebitOperation",
            fields=[],
            options={
                "verbose_name": "Correction Debit",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="DeathOperation",
            fields=[],
            options={
                "verbose_name": "Death",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="ExpenseOperation",
            fields=[],
            options={
                "verbose_name": "Expense",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="InternalTransferOperation",
            fields=[],
            options={
                "verbose_name": "Internal Transfer",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="LoanOperation",
            fields=[],
            options={
                "verbose_name": "Loan",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="LossCoverageOperation",
            fields=[],
            options={
                "verbose_name": "Loss Coverage",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="ProfitDistributionOperation",
            fields=[],
            options={
                "verbose_name": "Profit Distribution",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="ProjectFundingOperation",
            fields=[],
            options={
                "verbose_name": "Project Funding",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="ProjectRefundOperation",
            fields=[],
            options={
                "verbose_name": "Project Refund",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="PurchaseOperation",
            fields=[],
            options={
                "verbose_name": "Purchase",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="SaleOperation",
            fields=[],
            options={
                "verbose_name": "Sale",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="WorkerAdvanceOperation",
            fields=[],
            options={
                "verbose_name": "Worker Advance",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="FinancialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "max_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Financial Categories",
                "unique_together": {("name", "parent_entity")},
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ShareholderAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                ("percent", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="app_operation.financialperiod",
                    ),
                ),
                (
                    "shareholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shareholder_allocations",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shareholder Allocation",
                "verbose_name_plural": "Shareholder Allocations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period", "shareholder"),
                        name="unique_allocation_per_period_shareholder",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
