# Generated by Django 6.0.1 on 2026-03-22 12:07

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import apps.app_base.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_entity", "0012_auto_20260303_1436"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("CASH_INJECTION", "Cash Injection"),
                            ("CASH_WITHDRAWAL", "Cash Withdrawal"),
                            ("PROJECT_FUNDING", "Project Funding"),
                            ("PROJECT_REFUND", "Project Refund"),
                            ("PROFIT_DISTRIBUTION", "Profit Distribution"),
                            ("LOSS_COVERAGE", "Loss Coverage"),
                            ("INTERNAL_TRANSFER", "Internal Transfer"),
                            ("LOAN", "Loan"),
                            ("PURCHASE", "Purchase"),
                            ("SALE", "Sale"),
                            ("EXPENSE", "EXPENSE"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_incoming",
                        to="app_entity.entity",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_supervised",
                        to="app_entity.entity",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="app_operation.operation",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_outgoing",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation",
                "verbose_name_plural": "Operations",
                "ordering": ["-date", "-created_at"],
            },
            bases=(
                apps.app_base.mixins.ImmutableMixin,
                apps.app_base.mixins.AdjustableMixin,
                apps.app_base.mixins.AmountCleanMixin,
                apps.app_base.mixins.LinkedIssuanceTransactionMixin,
                apps.app_base.mixins.LinkedPaymentTransactionMixin,
                apps.app_base.mixins.OfficerMixin,
                apps.app_base.mixins.HasRelatedTransactions,
                models.Model,
            ),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
