# Generated by Django 6.0.1 on 2026-04-03 19:43

import apps.app_base.mixins
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_entity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("CASH_INJECTION", "Cash Injection"),
                            ("CASH_WITHDRAWAL", "Cash Withdrawal"),
                            ("PROJECT_FUNDING", "Project Funding"),
                            ("PROJECT_REFUND", "Project Refund"),
                            ("PROFIT_DISTRIBUTION", "Profit Distribution"),
                            ("LOSS_COVERAGE", "Loss Coverage"),
                            ("INTERNAL_TRANSFER", "Internal Transfer"),
                            ("LOAN", "Loan"),
                            ("PURCHASE", "Purchase"),
                            ("SALE", "Sale"),
                            ("EXPENSE", "EXPENSE"),
                            ("CAPITAL_GAIN", "CAPITAL_GAIN"),
                            ("CAPITAL_LOSS", "CAPITAL_LOSS"),
                            ("WORKER_ADVANCE", "WORKER_ADVANCE"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_incoming",
                        to="app_entity.entity",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_supervised",
                        to="app_entity.entity",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="app_operation.operation",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_outgoing",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation",
                "verbose_name_plural": "Operations",
                "ordering": ["-date", "-created_at"],
            },
            bases=(
                apps.app_base.mixins.ImmutableMixin,
                apps.app_base.mixins.AdjustableMixin,
                apps.app_base.mixins.AmountCleanMixin,
                apps.app_base.mixins.LinkedIssuanceTransactionMixin,
                apps.app_base.mixins.LinkedPaymentTransactionMixin,
                apps.app_base.mixins.LinkedRePaymentTransactionMixin,
                apps.app_base.mixins.OfficerMixin,
                apps.app_base.mixins.HasRelatedTransactions,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CapitalGainOperation",
            fields=[],
            options={
                "verbose_name": "Capital Gain",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="CapitalLossOperation",
            fields=[],
            options={
                "verbose_name": "Capital Loss",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="CashInjectionOperation",
            fields=[],
            options={
                "verbose_name": "Cash Injection",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="CashWithdrawalOperation",
            fields=[],
            options={
                "verbose_name": "Cash Withdrawal",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="ExpenseOperation",
            fields=[],
            options={
                "verbose_name": "Expense",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="InternalTransferOperation",
            fields=[],
            options={
                "verbose_name": "Internal Transfer",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="LoanOperation",
            fields=[],
            options={
                "verbose_name": "Loan",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="LossCoverageOperation",
            fields=[],
            options={
                "verbose_name": "Loss Coverage",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="ProfitDistributionOperation",
            fields=[],
            options={
                "verbose_name": "Profit Distribution",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="ProjectFundingOperation",
            fields=[],
            options={
                "verbose_name": "Project Funding",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="ProjectRefundOperation",
            fields=[],
            options={
                "verbose_name": "Project Refund",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="PurchaseOperation",
            fields=[],
            options={
                "verbose_name": "Purchase",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="SaleOperation",
            fields=[],
            options={
                "verbose_name": "Sale",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="WorkerAdvanceOperation",
            fields=[],
            options={
                "verbose_name": "Worker Advance",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="FinancialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("SALE", "Sale"),
                            ("EXPENSE", "Expense"),
                        ],
                        default="EXPENSE",
                        max_length=20,
                    ),
                ),
                (
                    "max_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Financial Categories",
                "unique_together": {("name", "parent_entity")},
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
