# Generated by Django 6.0.4 on 2026-04-20 18:43

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0001_initial"),
        ("app_operation", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="financialcategory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="financialcategory",
            name="category_type",
            field=models.CharField(
                choices=[("EXPENSE", "Expense"), ("INCOME", "Income")],
                default="EXPENSE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="financialcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="FinancialCategoriesEntitiesRelations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "max_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities_relations",
                        to="app_operation.financialcategory",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_categories_entities_relations",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Financial Categories Entities Relations",
                "unique_together": {("entity", "category")},
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="financialcategory",
            name="entity",
            field=models.ManyToManyField(
                related_name="categories",
                through="app_operation.FinancialCategoriesEntitiesRelations",
                to="app_entity.entity",
            ),
        ),
        migrations.RemoveField(
            model_name="financialcategory",
            name="max_limit",
        ),
        migrations.RemoveField(
            model_name="financialcategory",
            name="parent_entity",
        ),
    ]
