# Generated by Django 6.0.4 on 2026-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_operation", "0002_alter_financialcategory_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialcategoriesentitiesrelations",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="financialcategory",
            name="category_type",
            field=models.CharField(default="EXPENSE", editable=False, max_length=10),
        ),
    ]
