# Generated by Django 6.0.1 on 2026-04-13 10:48

import apps.app_base.mixins
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0002_remove_entity_can_pay_fund_active"),
        (
            "app_operation",
            "0002_correctioncreditoperation_correctiondebitoperation_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_periods",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Period",
                "verbose_name_plural": "Financial Periods",
                "ordering": ["entity", "-start_date"],
            },
            bases=(apps.app_base.mixins.ImmutableMixin, models.Model),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="operation",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="app_operation.financialperiod",
            ),
        ),
    ]
