# Generated by Django 6.0.4 on 2026-04-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_operation",
            "0003_financialcategoriesentitiesrelations_is_active_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialcategory",
            name="is_active",
        ),
    ]
