# Generated by Django 6.0.1 on 2026-04-13 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_operation", "0003_financialperiod_operation_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
