# Generated by Django 6.0.4 on 2026-04-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_operation", "0004_remove_financialcategory_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialcategory",
            name="aspect",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
