# Generated by Django 6.0.1 on 2026-04-13 12:15

import apps.app_base.mixins
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0002_remove_entity_can_pay_fund_active"),
        ("app_operation", "0004_alter_operation_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distribution_plans",
                        to="app_entity.entity",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distribution_plans",
                        to="app_operation.financialperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribution Plan",
                "verbose_name_plural": "Distribution Plans",
            },
            bases=(apps.app_base.mixins.ImmutableMixin, models.Model),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="operation",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="app_operation.distributionplan",
            ),
        ),
        migrations.CreateModel(
            name="ShareholderAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("percent", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="app_operation.distributionplan",
                    ),
                ),
                (
                    "shareholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shareholder_allocations",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shareholder Allocation",
                "verbose_name_plural": "Shareholder Allocations",
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="distributionplan",
            constraint=models.UniqueConstraint(
                fields=("entity", "period"),
                name="unique_distribution_plan_per_entity_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="shareholderallocation",
            constraint=models.UniqueConstraint(
                fields=("plan", "shareholder"),
                name="unique_allocation_per_plan_shareholder",
            ),
        ),
    ]
