# Generated by Django 6.0.1 on 2026-04-14 19:53

import apps.app_base.mixins
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0002_remove_entity_can_pay_fund_active"),
        ("app_operation", "0005_distribution_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfitLoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                "verbose_name": "Profit/Loss",
                "verbose_name_plural": "Profit/Losses",
            },
            bases=(apps.app_base.mixins.ImmutableMixin, models.Model),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="distributionplan",
            name="unique_distribution_plan_per_entity_period",
        ),
        migrations.AddField(
            model_name="profitloss",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profit_losses",
                to="app_entity.entity",
            ),
        ),
        migrations.AddField(
            model_name="profitloss",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profit_losses",
                to="app_operation.financialperiod",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="app_operation.profitloss",
            ),
        ),
        migrations.AlterField(
            model_name="shareholderallocation",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="app_operation.profitloss",
            ),
        ),
        migrations.RemoveField(
            model_name="distributionplan",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="distributionplan",
            name="period",
        ),
        migrations.AddConstraint(
            model_name="profitloss",
            constraint=models.UniqueConstraint(
                fields=("entity", "period"), name="unique_profit_loss_per_entity_period"
            ),
        ),
        migrations.DeleteModel(
            name="DistributionPlan",
        ),
    ]
