# Generated by Django 6.0.4 on 2026-04-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_operation", "0005_financialcategory_aspect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialcategory",
            name="entity",
        ),
        migrations.DeleteModel(
            name="FinancialCategoriesEntitiesRelations",
        ),
        migrations.DeleteModel(
            name="FinancialCategory",
        ),
    ]
