# Generated by Django 6.0.4 on 2026-05-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_operation", "0006_remove_financialcategory_entity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialperiod",
            name="amount",
        ),
    ]
