# Generated by Django 6.0.1 on 2026-04-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_operation", "0007_merge_profitloss_into_financialperiod"),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthOperation",
            fields=[],
            options={
                "verbose_name": "Birth",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.CreateModel(
            name="DeathOperation",
            fields=[],
            options={
                "verbose_name": "Death",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app_operation.operation",),
        ),
        migrations.AlterField(
            model_name="operation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("CASH_INJECTION", "Cash Injection"),
                    ("CASH_WITHDRAWAL", "Cash Withdrawal"),
                    ("PROJECT_FUNDING", "Project Funding"),
                    ("PROJECT_REFUND", "Project Refund"),
                    ("PROFIT_DISTRIBUTION", "Profit Distribution"),
                    ("LOSS_COVERAGE", "Loss Coverage"),
                    ("INTERNAL_TRANSFER", "Internal Transfer"),
                    ("LOAN", "Loan"),
                    ("PURCHASE", "Purchase"),
                    ("SALE", "Sale"),
                    ("EXPENSE", "EXPENSE"),
                    ("CAPITAL_GAIN", "CAPITAL_GAIN"),
                    ("CAPITAL_LOSS", "CAPITAL_LOSS"),
                    ("WORKER_ADVANCE", "WORKER_ADVANCE"),
                    ("CORRECTION_CREDIT", "Correction Credit"),
                    ("CORRECTION_DEBIT", "Correction Debit"),
                    ("BIRTH", "Birth"),
                    ("DEATH", "Death"),
                ],
                max_length=30,
            ),
        ),
    ]
