# Generated by Django 6.0.1 on 2026-08-09 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entity', '0004_alter_entity_entity_type'),
        ('app_operation', '0007_remove_financialperiod_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='app_entity.financialcategory'),
        ),
    ]
