# Generated by Django 6.0.1 on 2026-04-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_operation", "0008_birthoperation_deathoperation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialcategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="financialcategory",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="financialcategory",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="financialcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="financialperiod",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="financialperiod",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="financialperiod",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="financialperiod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_by",
                to="app_operation.operation",
                verbose_name="reversal of",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="shareholderallocation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="shareholderallocation",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="shareholderallocation",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="shareholderallocation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
