# Generated by Django 6.0.1 on 2026-08-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_operation', '0008_operation_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shareholderallocation',
            name='unique_allocation_per_period_shareholder',
        ),
        migrations.DeleteModel(
            name='LossCoverageOperation',
        ),
        migrations.DeleteModel(
            name='ProfitDistributionOperation',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='plan',
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('CASH_INJECTION', 'Cash Injection'), ('CASH_WITHDRAWAL', 'Cash Withdrawal'), ('PROJECT_FUNDING', 'Project Funding'), ('PROJECT_REFUND', 'Project Refund'), ('INTERNAL_TRANSFER', 'Internal Transfer'), ('LOAN', 'Loan'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('EXPENSE', 'EXPENSE'), ('CAPITAL_GAIN', 'CAPITAL_GAIN'), ('CAPITAL_LOSS', 'CAPITAL_LOSS'), ('WORKER_ADVANCE', 'WORKER_ADVANCE'), ('CORRECTION_CREDIT', 'Correction Credit'), ('CORRECTION_DEBIT', 'Correction Debit'), ('BIRTH', 'Birth'), ('DEATH', 'Death'), ('CONSUMPTION', 'Consumption')], max_length=30),
        ),
        migrations.DeleteModel(
            name='ShareholderAllocation',
        ),
    ]
