# Generated by Django 6.0.4 on 2026-04-20 17:57

import apps.app_base.mixins
import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_entity", "0001_initial"),
        ("app_operation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="date"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements_supervised",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="officer",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements",
                        to="app_operation.operation",
                        verbose_name="operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "inventory movement",
                "verbose_name_plural": "inventory movements",
                "ordering": ["-date", "-created_at"],
            },
            bases=(
                apps.app_base.mixins.ImmutableMixin,
                apps.app_base.mixins.OfficerMixin,
                models.Model,
            ),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="unit price"
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app_operation.operation",
                        verbose_name="operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice item",
                "verbose_name_plural": "invoice items",
            },
            bases=(apps.app_base.mixins.AmountCleanMixin, models.Model),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="InventoryMovementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="app_inventory.inventorymovement",
                        verbose_name="movement",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="app_inventory.inventorymovementline",
                        verbose_name="reversal of",
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movement_lines",
                        to="app_inventory.invoiceitem",
                        verbose_name="invoice item",
                    ),
                ),
            ],
            options={
                "verbose_name": "inventory movement line",
                "verbose_name_plural": "inventory movement lines",
            },
            bases=(apps.app_base.mixins.ImmutableMixin, models.Model),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="name (Arabic)"
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("ANIMAL", "Livestock Asset"),
                            ("FEED", "Consumable"),
                            ("MEDICINE", "Biological"),
                            ("PRODUCT", "Production Output"),
                        ],
                        default="ANIMAL",
                        max_length=20,
                        verbose_name="nature",
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        default="General", max_length=20, verbose_name="sub_category"
                    ),
                ),
                (
                    "default_unit",
                    models.CharField(
                        default="Head", max_length=20, verbose_name="default unit"
                    ),
                ),
                (
                    "requires_individual_tag",
                    models.BooleanField(
                        default=False, verbose_name="requires individual tag"
                    ),
                ),
                (
                    "tracking_mode",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual (Tag ID)"),
                            ("BATCH", "Batch/Group"),
                            ("COMMODITY", "Quantity (Weight/Volume)"),
                        ],
                        default="BATCH",
                        max_length=24,
                        verbose_name="tracking mode",
                    ),
                ),
                (
                    "entities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="product_templates",
                        to="app_entity.entity",
                        verbose_name="entities",
                    ),
                ),
            ],
            options={
                "verbose_name": "product template",
                "verbose_name_plural": "product templates",
                "unique_together": {
                    (
                        "name",
                        "nature",
                        "sub_category",
                        "default_unit",
                        "tracking_mode",
                        "requires_individual_tag",
                    )
                },
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "unique_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="unique id",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="quantity"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="unit price"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="app_entity.entity",
                        verbose_name="entity",
                    ),
                ),
                (
                    "invoice_items",
                    models.ManyToManyField(
                        related_name="products",
                        to="app_inventory.invoiceitem",
                        verbose_name="invoice items",
                    ),
                ),
                (
                    "product_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_inventory.producttemplate",
                        verbose_name="product template",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
            bases=(apps.app_base.mixins.AmountCleanMixin, models.Model),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="app_inventory.producttemplate",
                verbose_name="product",
            ),
        ),
        migrations.CreateModel(
            name="ProductLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("SALE", "Sale"),
                            ("BIRTH", "Birth"),
                            ("DEATH", "Death"),
                            ("CAPITAL_GAIN", "Capital Gain"),
                            ("CAPITAL_LOSS", "Capital Loss"),
                            ("REVERSAL", "Reversal"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=20,
                        verbose_name="entry type",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "quantity_delta",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="quantity delta"
                    ),
                ),
                (
                    "value_delta",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="value delta"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="idempotency key"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="app_inventory.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product ledger entry",
                "verbose_name_plural": "product ledger entries",
                "indexes": [
                    models.Index(
                        fields=["product", "date"],
                        name="app_invento_product_7eceba_idx",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
