# Generated by Django 6.0.1 on 2026-04-15 13:58

import datetime
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0002_remove_entity_can_pay_fund_active"),
        ("app_inventory", "0001_initial"),
        ("app_operation", "0008_birthoperation_deathoperation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="operation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="app_operation.operation",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tracking_mode",
            field=models.CharField(
                choices=[
                    ("INDIVIDUAL", "Individual (Tag ID)"),
                    ("BATCH", "Batch/Group"),
                    ("COMMODITY", "Quantity (Weight/Volume)"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("tag_id", models.CharField(db_index=True, max_length=50, unique=True)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "invoice_items",
                    models.ManyToManyField(
                        related_name="animals", to="app_inventory.invoiceitem"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_inventory.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("initial_quantity", models.PositiveIntegerField()),
                ("current_quantity", models.PositiveIntegerField()),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "invoice_items",
                    models.ManyToManyField(
                        related_name="batches", to="app_inventory.invoiceitem"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_inventory.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("date", models.DateField(db_index=True, default=datetime.date.today)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("notes", models.TextField(blank=True)),
                (
                    "animal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="app_inventory.animal",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="app_inventory.batch",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_entity.entity",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name="ProductEvaluation",
        ),
        migrations.AddConstraint(
            model_name="evaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("animal__isnull", False), ("batch__isnull", True)),
                    models.Q(("animal__isnull", True), ("batch__isnull", False)),
                    _connector="OR",
                ),
                name="evaluation_requires_exactly_one_target",
            ),
        ),
    ]
