# Generated by Django 6.0.4 on 2026-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productledgerentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Purchase"),
                    ("SALE", "Sale"),
                    ("BIRTH", "Birth"),
                    ("DEATH", "Death"),
                    ("CONSUMPTION", "Consumption"),
                    ("CAPITAL_GAIN", "Capital Gain"),
                    ("CAPITAL_LOSS", "Capital Loss"),
                    ("REVERSAL", "Reversal"),
                    ("ADJUSTMENT", "Adjustment"),
                ],
                max_length=20,
                verbose_name="entry type",
            ),
        ),
    ]
