# Generated by Django 6.0.1 on 2026-04-15 14:23

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_inventory",
            "0002_alter_invoice_operation_alter_product_tracking_mode_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "tracking_mode",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual (Tag ID)"),
                            ("BATCH", "Batch/Group"),
                            ("COMMODITY", "Quantity (Weight/Volume)"),
                        ],
                        max_length=24,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="animal",
            name="invoice_items",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="product",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="invoice_items",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="product",
        ),
        migrations.RemoveConstraint(
            model_name="evaluation",
            name="evaluation_requires_exactly_one_target",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tracking_mode",
        ),
        migrations.AddField(
            model_name="product",
            name="invoice_items",
            field=models.ManyToManyField(
                related_name="products", to="app_inventory.invoiceitem"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="unique_id",
            field=models.CharField(
                db_index=True, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app_inventory.category"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_template",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="app_inventory.producttemplate",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="app_inventory.producttemplate",
            ),
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="animal",
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="evaluator",
        ),
        migrations.DeleteModel(
            name="Animal",
        ),
        migrations.DeleteModel(
            name="Batch",
        ),
        migrations.DeleteModel(
            name="Evaluation",
        ),
    ]
