# Generated by Django 6.0.4 on 2026-05-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0002_alter_productledgerentry_entry_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovementline",
            name="group_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Key shared by movement lines that were created together. Used for display/grouping purposes only.",
                max_length=32,
                verbose_name="group key",
            ),
        ),
    ]
