# Generated by Django 6.0.1 on 2026-04-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0002_remove_entity_can_pay_fund_active"),
        ("app_inventory", "0003_producttemplate_remove_animal_invoice_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="entities",
            field=models.ManyToManyField(
                related_name="product_categories", to="app_entity.entity"
            ),
        ),
    ]
