# Generated by Django 6.0.4 on 2026-05-07 23:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0003_add_group_key_to_inventorymovementline"),
        ("app_operation", "0007_remove_financialperiod_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorymovementline",
            name="movement",
        ),
        migrations.AlterModelOptions(
            name="inventorymovementline",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "inventory movement line",
                "verbose_name_plural": "inventory movement lines",
            },
        ),
        migrations.AddField(
            model_name="inventorymovementline",
            name="date",
            field=models.DateField(default=datetime.date.today, verbose_name="date"),
        ),
        migrations.AddField(
            model_name="inventorymovementline",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AddField(
            model_name="inventorymovementline",
            name="operation",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movement_lines",
                to="app_operation.operation",
                verbose_name="operation",
                null=True,
                blank=True,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="InventoryMovement",
        ),
    ]
