# Generated by Django 6.0.4 on 2026-05-07 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0004_remove_inventorymovementline_movement_and_more"),
        ("app_operation", "0007_remove_financialperiod_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovementline",
            name="operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movement_lines",
                to="app_operation.operation",
                verbose_name="operation",
            ),
        ),
    ]
