# Generated by Django 6.0.1 on 2026-04-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0004_category_entities"),
        ("app_operation", "0009_alter_financialcategory_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttemplate",
            name="category",
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={"verbose_name": "invoice", "verbose_name_plural": "invoices"},
        ),
        migrations.AlterModelOptions(
            name="invoiceitem",
            options={
                "verbose_name": "invoice item",
                "verbose_name_plural": "invoice items",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "product", "verbose_name_plural": "products"},
        ),
        migrations.AlterModelOptions(
            name="producttemplate",
            options={
                "verbose_name": "product template",
                "verbose_name_plural": "product templates",
            },
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="default_unit",
            field=models.CharField(
                default="Head", max_length=20, verbose_name="default unit"
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="nature",
            field=models.CharField(
                choices=[
                    ("ANIMAL", "Livestock Asset"),
                    ("FEED", "Consumable"),
                    ("MEDICINE", "Biological"),
                    ("PRODUCT", "Production Output"),
                ],
                default="ANIMAL",
                max_length=20,
                verbose_name="nature",
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="requires_individual_tag",
            field=models.BooleanField(
                default=False, verbose_name="requires individual tag"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="operation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="app_operation.operation",
                verbose_name="operation",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="app_inventory.invoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="app_inventory.producttemplate",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="quantity"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="unit price"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="product",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="invoice_items",
            field=models.ManyToManyField(
                related_name="products",
                to="app_inventory.invoiceitem",
                verbose_name="invoice items",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="app_inventory.producttemplate",
                verbose_name="product template",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="quantity"),
        ),
        migrations.AlterField(
            model_name="product",
            name="unique_id",
            field=models.CharField(
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="unique id",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="unit price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="producttemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="producttemplate",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="producttemplate",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="producttemplate",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="producttemplate",
            name="tracking_mode",
            field=models.CharField(
                choices=[
                    ("INDIVIDUAL", "Individual (Tag ID)"),
                    ("BATCH", "Batch/Group"),
                    ("COMMODITY", "Quantity (Weight/Volume)"),
                ],
                default="BATCH",
                max_length=24,
                verbose_name="tracking mode",
            ),
        ),
        migrations.AlterField(
            model_name="producttemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
