# Generated by Django 6.0.1 on 2026-04-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0003_alter_contactinfo_options_alter_entity_options_and_more"),
        ("app_inventory", "0005_remove_producttemplate_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="entities",
            field=models.ManyToManyField(
                blank=True,
                related_name="product_templates",
                to="app_entity.entity",
                verbose_name="entities",
            ),
        ),
    ]
