# Generated by Django 6.0.1 on 2026-05-08 22:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0005_alter_inventorymovementline_operation"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="has_tag",
            field=models.BooleanField(default=False, verbose_name="has tag"),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="minimum_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Smallest allowed quantity increment. Used as the `step` attribute on number inputs in forms.",
                max_digits=10,
                verbose_name="minimum quantity",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="producttemplate",
            unique_together={
                (
                    "name",
                    "nature",
                    "sub_category",
                    "default_unit",
                    "tracking_mode",
                    "has_tag",
                )
            },
        ),
        migrations.RemoveField(
            model_name="producttemplate",
            name="requires_individual_tag",
        ),
    ]
