# Generated by Django 6.0.1 on 2026-04-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0006_producttemplate_entities"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="name_ar",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="name (Arabic)"
            ),
        ),
    ]
