# Generated by Django 6.0.1 on 2026-05-09 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0007_inventorymovementline_product_officer_and_more"),
        ("app_operation", "0007_remove_financialperiod_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovementline",
            name="group_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short hex string grouping lines created together.",
                max_length=32,
                verbose_name="group key",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovementline",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movement_lines",
                to="app_operation.operation",
                verbose_name="operation",
            ),
        ),
    ]
