# Generated by Django 6.0.1 on 2026-04-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0007_producttemplate_name_ar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unique_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="unique id",
            ),
        ),
    ]
