# Generated by Django 6.0.1 on 2026-05-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0008_alter_inventorymovementline_group_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productledgerentry",
            name="invoice_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="app_inventory.invoiceitem",
                verbose_name="invoice item",
            ),
        ),
        migrations.AlterField(
            model_name="productledgerentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE_ISSUANCE", "Purchase Issuance"),
                    ("SALE_ISSUANCE", "Sale Issuance"),
                    ("BIRTH_ISSUANCE", "Birth Issuance"),
                    ("DEATH_ISSUANCE", "Death Issuance"),
                    ("CONSUMPTION_ISSUANCE", "Consumption Issuance"),
                    ("PURCHASE_MOVEMENT", "Purchase Movement"),
                    ("SALE_MOVEMENT", "Sale Movement"),
                    ("BIRTH_MOVEMENT", "Birth Movement"),
                    ("DEATH_MOVEMENT", "Death Movement"),
                    ("CONSUMPTION_MOVEMENT", "Consumption Movement"),
                    ("PURCHASE_ADJ_INC", "Purchase Adjustment Increase"),
                    ("PURCHASE_ADJ_DEC", "Purchase Adjustment Decrease"),
                    ("SALE_ADJ_INC", "Sale Adjustment Increase"),
                    ("SALE_ADJ_DEC", "Sale Adjustment Decrease"),
                    ("CAPITAL_GAIN", "Capital Gain"),
                    ("CAPITAL_LOSS", "Capital Loss"),
                    ("REVERSAL", "Reversal"),
                ],
                max_length=30,
                verbose_name="entry type",
            ),
        ),
        migrations.AlterField(
            model_name="productledgerentry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="app_inventory.product",
                verbose_name="product",
            ),
        ),
        migrations.AddIndex(
            model_name="productledgerentry",
            index=models.Index(
                fields=["invoice_item", "entry_type"],
                name="app_invento_invoice_a251d5_idx",
            ),
        ),
    ]
