# Generated by Django 6.0.1 on 2026-04-16 12:34

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0008_alter_product_unique_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("SALE", "Sale"),
                            ("BIRTH", "Birth"),
                            ("DEATH", "Death"),
                            ("CAPITAL_GAIN", "Capital Gain"),
                            ("CAPITAL_LOSS", "Capital Loss"),
                            ("REVERSAL", "Reversal"),
                        ],
                        max_length=20,
                        verbose_name="entry type",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "quantity_delta",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="quantity delta"
                    ),
                ),
                (
                    "value_delta",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="value delta"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="idempotency key"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="app_inventory.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product ledger entry",
                "verbose_name_plural": "product ledger entries",
                "indexes": [
                    models.Index(
                        fields=["product", "date"],
                        name="app_invento_product_7eceba_idx",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
