# Generated by Django 6.0.1 on 2026-08-10 11:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entity', '0004_alter_entity_entity_type'),
        ('app_inventory', '0009_ledger_entry_type_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='minimum_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Smallest allowed quantity increment. Used as the `step` attribute on number inputs in forms and enforced on invoice/movement quantities (e.g. 1 for Head, 0.01 for Kg).', max_digits=10, verbose_name='minimum quantity'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('unique_id__isnull', False)), fields=('entity', 'unique_id'), name='unique_product_tag_per_entity'),
        ),
    ]
