# Generated by Django 6.0.1 on 2026-08-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0010_alter_producttemplate_minimum_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='tag_prefix',
            field=models.CharField(blank=True, default='', help_text='Prefix used to auto-generate unique tags for individually tracked animals (e.g. CALF, COW, LAMB). If blank, it is derived from the template name.', max_length=20, verbose_name='tag prefix'),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='tracking_mode',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual (Tag ID)'), ('COMMODITY', 'Quantity (Weight/Volume)')], default='INDIVIDUAL', help_text='Resolved automatically from nature: ANIMAL → INDIVIDUAL, otherwise COMMODITY.', max_length=24, verbose_name='tracking mode'),
        ),
    ]
