# Generated by Django 6.0.1 on 2026-04-17 12:24

import apps.app_base.mixins
import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0011_remove_invoice"),
        ("app_operation", "0011_invoiceitemadjustment_invoiceitemadjustmentline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="date"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements_supervised",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="officer",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements",
                        to="app_operation.operation",
                        verbose_name="operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "inventory movement",
                "verbose_name_plural": "inventory movements",
                "ordering": ["-date", "-created_at"],
            },
            bases=(
                apps.app_base.mixins.ImmutableMixin,
                apps.app_base.mixins.OfficerMixin,
                models.Model,
            ),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="InventoryMovementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movement_lines",
                        to="app_inventory.invoiceitem",
                        verbose_name="invoice item",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="app_inventory.inventorymovement",
                        verbose_name="movement",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="app_inventory.inventorymovementline",
                        verbose_name="reversal of",
                    ),
                ),
            ],
            options={
                "verbose_name": "inventory movement line",
                "verbose_name_plural": "inventory movement lines",
            },
            bases=(apps.app_base.mixins.ImmutableMixin, models.Model),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
