# Generated by Django 6.0.1 on 2026-08-10 16:25

import datetime
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0011_producttemplate_tag_prefix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Individual animal sex; defaults from the template when born.', max_length=10, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='product',
            name='mother',
            field=models.ForeignKey(blank=True, help_text='Mother animal that gave birth to this animal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='app_inventory.product', verbose_name='mother'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='animal_type',
            field=models.CharField(blank=True, default='', help_text='Species/type of animal, e.g. Cow, Buffalo, Sheep, Goat.', max_length=50, verbose_name='animal type'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='can_be_consumed',
            field=models.BooleanField(default=True, help_text='Whether this product can be consumed. No animal can be consumed (forced to False for ANIMAL templates).', verbose_name='can be consumed'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='can_die',
            field=models.BooleanField(default=True, help_text='Whether this product can die. All animals can die.', verbose_name='can die'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('MIXED', 'Mixed'), ('NA', 'Not applicable')], default='NA', help_text='Default gender for animals created from this template (MALE/FEMALE/MIXED). NA for non-animal templates.', max_length=10, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='gives_birth_to',
            field=models.ForeignKey(blank=True, help_text='Offspring template produced at birth (e.g. Dairy Cow → Calf). Only valid for ANIMAL templates with gender FEMALE or MIXED.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='born_from', to='app_inventory.producttemplate', verbose_name='gives birth to'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='produces',
            field=models.ManyToManyField(blank=True, help_text='Output templates this animal can produce (e.g. Milk, Manure). Metadata only — no production operation yet.', related_name='produced_by', to='app_inventory.producttemplate', verbose_name='produces'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted at')),
                ('deletable', models.BooleanField(default=False, verbose_name='deletable')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('record_type', models.CharField(choices=[('CHECKUP', 'Check-up'), ('VACCINATION', 'Vaccination'), ('TREATMENT', 'Treatment'), ('DIAGNOSIS', 'Diagnosis'), ('OTHER', 'Other')], max_length=20, verbose_name='record type')),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('SICK', 'Sick'), ('UNDER_TREATMENT', 'Under treatment'), ('RECOVERED', 'Recovered'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Health status at the time this record was made.', max_length=20, verbose_name='status')),
                ('next_due_date', models.DateField(blank=True, help_text='e.g. next vaccination.', null=True, verbose_name='next due date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='officer')),
                ('product', models.ForeignKey(help_text='The animal this medical record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='app_inventory.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'medical record',
                'verbose_name_plural': 'medical records',
                'ordering': ['-date', '-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
