# Generated by Django 6.0.1 on 2026-04-17 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0008_delete_fund"),
        ("app_inventory", "0012_add_inventory_movement"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="app_entity.entity",
                verbose_name="entity",
            ),
        ),
    ]
