# Generated by Django 6.0.1 on 2026-04-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0013_product_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="sub_caytegory",
            field=models.CharField(
                default="General", max_length=20, verbose_name="sub_caytegory"
            ),
        ),
    ]
