# Generated by Django 6.0.1 on 2026-08-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0013_move_medical_record'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productledgerentry',
            name='app_invento_product_7eceba_idx',
        ),
        migrations.RemoveIndex(
            model_name='productledgerentry',
            name='app_invento_invoice_a251d5_idx',
        ),
        migrations.DeleteModel(
            name='ProductLedgerEntry',
        ),
    ]
