# Generated by Django 6.0.1 on 2026-03-07 22:49

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models

import apps.app_base.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_entity", "0012_auto_20260303_1436"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("REVENUE", "REVENUE"),
                            ("OTHER_INCOME", "OTHER_INCOME"),
                            ("TAX_PAYMENT", "TAX_PAYMENT"),
                            ("INVOICE_ADJUSTMENT", "INVOICE_ADJUSTMENT"),
                            ("EXPENSE_ADJUSTMENT", "EXPENSE_ADJUSTMENT"),
                            ("PAYROLL_ADJUSTMENT", "PAYROLL_ADJUSTMENT"),
                            ("PURCHASE", "PURCHASE"),
                            ("PURCHASE_PAYMENT", "PURCHASE_PAYMENT"),
                            ("PURCHASE_RETURN", "PURCHASE_RETURN"),
                            ("SALE", "SALE"),
                            ("EXPENSE", "EXPENSE"),
                            ("EXPENSE_PAYMENT", "EXPENSE_PAYMENT"),
                            ("WORKER_WAGE", "WORKER_WAGE"),
                            ("SALARY_INCOME", "SALARY_INCOME"),
                            ("WORKER_ADVANCE", "WORKER_ADVANCE"),
                            ("ADVANCE_RECEIPT", "WORKER_ADVANCE"),
                            ("ADVANCE_REPAYMENT", "ADVANCE_REPAYMENT"),
                            ("ADVANCE_COLLECTION", "ADVANCE_COLLECTION"),
                            ("CAPITAL_INJECTION", "CAPITAL_INJECTION"),
                            ("CAPITAL_WITHDRAWAL", "CAPITAL_WITHDRAWAL"),
                            ("CAPITAL_GAIN", "CAPITAL_GAIN"),
                            ("CAPITAL_LOSS", "CAPITAL_LOSS"),
                            ("PROFIT_DISTRIBUTION", "PROFIT_DISTRIBUTION"),
                            ("PROFIT_COLLECTION", "PROFIT_COLLECTION"),
                            ("PROJECT_FUNDING", "PROJECT_FUNDING"),
                            ("PROJECT_REFUND", "PROJECT_REFUND"),
                            ("LOAN_ISSUANCE", "LOAN_ISSUANCE"),
                            ("LOAN_RECEIVED_BY_OTHER", "LOAN_RECEIVED_BY_OTHER"),
                            ("LOAN_REPAYMENT_BY_OTHER", "LOAN_REPAYMENT_BY_OTHER"),
                            ("LOAN_RECOVERY", "LOAN_RECOVERY"),
                            ("DEBT_RECEIVED", "DEBT_RECEIVED"),
                            ("DEBT_GIVEN_BY_LENDER", "DEBT_GIVEN_BY_LENDER"),
                            ("DEBT_PAYMENT", "DEBT_PAYMENT"),
                            ("DEBT_SETTLEMENT_BY_LENDER", "DEBT_SETTLEMENT_BY_LENDER"),
                            ("INTERNAL_TRANSFER", "INTERNAL_TRANSFER"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("description", models.TextField()),
                ("note", models.TextField(blank=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_by",
                        to="app_transaction.transaction",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_outgoing",
                        to="app_entity.fund",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_incoming",
                        to="app_entity.fund",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                apps.app_base.mixins.AmountCleanMixin,
                apps.app_base.mixins.ImmutableMixin,
                models.Model,
            ),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
