# Generated by Django 6.0.1 on 2026-04-03 19:43

import apps.app_base.mixins
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_entity", "0001_initial"),
        ("contenttypes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_ISSUANCE", "PURCHASE_ISSUANCE"),
                            ("PURCHASE_PAYMENT", "PURCHASE_PAYMENT"),
                            ("PURCHASE_ADJUSTMENT", "PURCHASE_ADJUSTMENT"),
                            ("SALE_ISSUANCE", "SALE_ISSUANCE"),
                            ("SALE_COLLECTION", "SALE_COLLECTION"),
                            ("SALE_ADJUSTMENT", "SALE_ADJUSTMENT"),
                            ("EXPENSE_ISSUANCE", "EXPENSE_ISSUANCE"),
                            ("EXPENSE_PAYMENT", "EXPENSE_PAYMENT"),
                            ("EXPENSE_ADJUSTMENT", "EXPENSE_ADJUSTMENT"),
                            ("WORKER_ADVANCE_ISSUANCE", "WORKER_ADVANCE_ISSUANCE"),
                            ("WORKER_ADVANCE_PAYMENT", "WORKER_ADVANCE_PAYMENT"),
                            (
                                "WORKER_ADVANCE_REPAYMENT_PAYEMENT",
                                "WORKER_ADVANCE_REPAYMENT_PAYEMENT",
                            ),
                            (
                                "CAPITAL_INJECTION_ISSUANCE",
                                "CAPITAL_INJECTION_ISSUANCE",
                            ),
                            ("CAPITAL_INJECTION_PAYMENT", "CAPITAL_INJECTION_PAYMENT"),
                            (
                                "CAPITAL_WITHDRAWAL_ISSUANCE",
                                "CAPITAL_WITHDRAWAL_ISSUANCE",
                            ),
                            (
                                "CAPITAL_WITHDRAWAL_PAYMENT",
                                "CAPITAL_WITHDRAWAL_PAYMENT",
                            ),
                            ("CAPITAL_GAIN_ISSUANCE", "CAPITAL_GAIN_ISSUANCE"),
                            ("CAPITAL_GAIN_PAYMENT", "CAPITAL_GAIN_PAYMENT"),
                            ("CAPITAL_LOSS_ISSUANCE", "CAPITAL_LOSS_ISSUANCE"),
                            ("CAPITAL_LOSS_PAYMENT", "CAPITAL_LOSS_PAYMENT"),
                            ("LOSS_COVERAGE_ISSUANCE", "LOSS_COVERAGE_ISSUANCE"),
                            ("LOSS_COVERAGE_PAYMENT", "LOSS_COVERAGE_PAYMENT"),
                            (
                                "PROFIT_DISTRIBUTION_ISSUANCE",
                                "PROFIT_DISTRIBUTION_ISSUANCE",
                            ),
                            (
                                "PROFIT_DISTRIBUTION_PAYMENT",
                                "PROFIT_DISTRIBUTION_PAYMENT",
                            ),
                            ("PROJECT_FUNDING_ISSUANCE", "PROJECT_FUNDING_ISSUANCE"),
                            ("PROJECT_FUNDING_PAYMENT", "PROJECT_FUNDING_PAYMENT"),
                            ("PROJECT_REFUND_ISSUANCE", "PROJECT_REFUND_ISSUANCE"),
                            ("PROJECT_REFUND_PAYMENT", "PROJECT_REFUND_PAYMENT"),
                            ("LOAN_ISSUANCE", "LOAN_ISSUANCE"),
                            ("LOAN_PAYMENT", "LOAN_PAYMENT"),
                            ("LOAN_REPAYMENT", "LOAN_REPAYMENT"),
                            (
                                "INTERNAL_TRANSFER_ISSUANCE",
                                "INTERNAL_TRANSFER_ISSUANCE",
                            ),
                            ("INTERNAL_TRANSFER_PAYMENT", "INTERNAL_TRANSFER_PAYMENT"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("description", models.TextField()),
                ("note", models.TextField(blank=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_supervised",
                        to="app_entity.entity",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_by",
                        to="app_transaction.transaction",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_outgoing",
                        to="app_entity.fund",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_incoming",
                        to="app_entity.fund",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                apps.app_base.mixins.AmountCleanMixin,
                apps.app_base.mixins.ImmutableMixin,
                models.Model,
            ),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
