# Generated by Django 6.0.1 on 2026-03-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("REVENUE", "REVENUE"),
                    ("OTHER_INCOME", "OTHER_INCOME"),
                    ("TAX_PAYMENT", "TAX_PAYMENT"),
                    ("INVOICE_ADJUSTMENT", "INVOICE_ADJUSTMENT"),
                    ("EXPENSE_ADJUSTMENT", "EXPENSE_ADJUSTMENT"),
                    ("PAYROLL_ADJUSTMENT", "PAYROLL_ADJUSTMENT"),
                    ("PURCHASE", "PURCHASE"),
                    ("PURCHASE_PAYMENT", "PURCHASE_PAYMENT"),
                    ("PURCHASE_RETURN", "PURCHASE_RETURN"),
                    ("SALE", "SALE"),
                    ("EXPENSE", "EXPENSE"),
                    ("EXPENSE_PAYMENT", "EXPENSE_PAYMENT"),
                    ("WORKER_WAGE", "WORKER_WAGE"),
                    ("SALARY_INCOME", "SALARY_INCOME"),
                    ("WORKER_ADVANCE", "WORKER_ADVANCE"),
                    ("ADVANCE_RECEIPT", "WORKER_ADVANCE"),
                    ("ADVANCE_REPAYMENT", "ADVANCE_REPAYMENT"),
                    ("ADVANCE_COLLECTION", "ADVANCE_COLLECTION"),
                    ("CAPITAL_INJECTION_ISSUANCE", "CAPITAL_INJECTION_ISSUANCE"),
                    ("CAPITAL_INJECTION_PAYMENT", "CAPITAL_INJECTION_PAYMENT"),
                    ("CAPITAL_WITHDRAWAL_ISSUANCE", "CAPITAL_WITHDRAWAL_ISSUANCE"),
                    ("CAPITAL_GAIN_ISSUANCE", "CAPITAL_GAIN_ISSUANCE"),
                    ("CAPITAL_LOSS_ISSUANCE", "CAPITAL_LOSS_ISSUANCE"),
                    ("PROFIT_DISTRIBUTION", "PROFIT_DISTRIBUTION"),
                    ("PROFIT_COLLECTION", "PROFIT_COLLECTION"),
                    ("PROJECT_FUNDING", "PROJECT_FUNDING"),
                    ("PROJECT_REFUND", "PROJECT_REFUND"),
                    ("LOAN_ISSUANCE", "LOAN_ISSUANCE"),
                    ("LOAN_RECEIVED_BY_OTHER", "LOAN_RECEIVED_BY_OTHER"),
                    ("LOAN_REPAYMENT_BY_OTHER", "LOAN_REPAYMENT_BY_OTHER"),
                    ("LOAN_RECOVERY", "LOAN_RECOVERY"),
                    ("DEBT_RECEIVED", "DEBT_RECEIVED"),
                    ("DEBT_GIVEN_BY_LENDER", "DEBT_GIVEN_BY_LENDER"),
                    ("DEBT_PAYMENT", "DEBT_PAYMENT"),
                    ("DEBT_SETTLEMENT_BY_LENDER", "DEBT_SETTLEMENT_BY_LENDER"),
                    ("INTERNAL_TRANSFER", "INTERNAL_TRANSFER"),
                ],
                max_length=50,
            ),
        ),
    ]
