# Generated by Django 6.0.1 on 2026-04-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_transaction", "0002_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("PURCHASE_ISSUANCE", "PURCHASE_ISSUANCE"),
                    ("PURCHASE_PAYMENT", "PURCHASE_PAYMENT"),
                    ("PURCHASE_ADJUSTMENT", "PURCHASE_ADJUSTMENT"),
                    ("SALE_ISSUANCE", "SALE_ISSUANCE"),
                    ("SALE_COLLECTION", "SALE_COLLECTION"),
                    ("SALE_ADJUSTMENT", "SALE_ADJUSTMENT"),
                    ("EXPENSE_ISSUANCE", "EXPENSE_ISSUANCE"),
                    ("EXPENSE_PAYMENT", "EXPENSE_PAYMENT"),
                    ("EXPENSE_ADJUSTMENT", "EXPENSE_ADJUSTMENT"),
                    ("WORKER_ADVANCE_ISSUANCE", "WORKER_ADVANCE_ISSUANCE"),
                    ("WORKER_ADVANCE_PAYMENT", "WORKER_ADVANCE_PAYMENT"),
                    (
                        "WORKER_ADVANCE_REPAYMENT_PAYEMENT",
                        "WORKER_ADVANCE_REPAYMENT_PAYEMENT",
                    ),
                    ("CASH_INJECTION_ISSUANCE", "CASH_INJECTION_ISSUANCE"),
                    ("CASH_INJECTION_PAYMENT", "CASH_INJECTION_PAYMENT"),
                    ("CAPITAL_WITHDRAWAL_ISSUANCE", "CAPITAL_WITHDRAWAL_ISSUANCE"),
                    ("CAPITAL_WITHDRAWAL_PAYMENT", "CAPITAL_WITHDRAWAL_PAYMENT"),
                    ("CAPITAL_GAIN_ISSUANCE", "CAPITAL_GAIN_ISSUANCE"),
                    ("CAPITAL_GAIN_PAYMENT", "CAPITAL_GAIN_PAYMENT"),
                    ("CAPITAL_LOSS_ISSUANCE", "CAPITAL_LOSS_ISSUANCE"),
                    ("CAPITAL_LOSS_PAYMENT", "CAPITAL_LOSS_PAYMENT"),
                    ("LOSS_COVERAGE_ISSUANCE", "LOSS_COVERAGE_ISSUANCE"),
                    ("LOSS_COVERAGE_PAYMENT", "LOSS_COVERAGE_PAYMENT"),
                    ("PROFIT_DISTRIBUTION_ISSUANCE", "PROFIT_DISTRIBUTION_ISSUANCE"),
                    ("PROFIT_DISTRIBUTION_PAYMENT", "PROFIT_DISTRIBUTION_PAYMENT"),
                    ("PROJECT_FUNDING_ISSUANCE", "PROJECT_FUNDING_ISSUANCE"),
                    ("PROJECT_FUNDING_PAYMENT", "PROJECT_FUNDING_PAYMENT"),
                    ("PROJECT_REFUND_ISSUANCE", "PROJECT_REFUND_ISSUANCE"),
                    ("PROJECT_REFUND_PAYMENT", "PROJECT_REFUND_PAYMENT"),
                    ("LOAN_ISSUANCE", "LOAN_ISSUANCE"),
                    ("LOAN_PAYMENT", "LOAN_PAYMENT"),
                    ("LOAN_REPAYMENT", "LOAN_REPAYMENT"),
                    ("CORRECTION_CREDIT_ISSUANCE", "CORRECTION_CREDIT_ISSUANCE"),
                    ("CORRECTION_CREDIT_PAYMENT", "CORRECTION_CREDIT_PAYMENT"),
                    ("CORRECTION_DEBIT_ISSUANCE", "CORRECTION_DEBIT_ISSUANCE"),
                    ("CORRECTION_DEBIT_PAYMENT", "CORRECTION_DEBIT_PAYMENT"),
                    ("INTERNAL_TRANSFER_ISSUANCE", "INTERNAL_TRANSFER_ISSUANCE"),
                    ("INTERNAL_TRANSFER_PAYMENT", "INTERNAL_TRANSFER_PAYMENT"),
                ],
                max_length=50,
            ),
        ),
    ]
