# Generated by Django 6.0.1 on 2026-03-08 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0012_auto_20260303_1436"),
        ("app_transaction", "0002_alter_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="officer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions_supervised",
                to="app_entity.entity",
            ),
            preserve_default=False,
        ),
    ]
