# Generated by Django 6.0.1 on 2026-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_transaction", "0005_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
