# Generated by Django 6.0.1 on 2026-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_transaction", "0005_alter_transaction_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("REVENUE", "REVENUE"),
                    ("OTHER_INCOME", "OTHER_INCOME"),
                    ("TAX_PAYMENT", "TAX_PAYMENT"),
                    ("INVOICE_ADJUSTMENT", "INVOICE_ADJUSTMENT"),
                    ("EXPENSE_ADJUSTMENT", "EXPENSE_ADJUSTMENT"),
                    ("PAYROLL_ADJUSTMENT", "PAYROLL_ADJUSTMENT"),
                    ("PURCHASE_ISSUANCE", "PURCHASE_ISSUANCE"),
                    ("PURCHASE_PAYMENT", "PURCHASE_PAYMENT"),
                    ("PURCHASE_RETURN", "PURCHASE_RETURN"),
                    ("SALE_ISSUANCE", "SALE_ISSUANCE"),
                    ("EXPENSE_ISSUANCE", "EXPENSE_ISSUANCE"),
                    ("EXPENSE_PAYMENT", "EXPENSE_PAYMENT"),
                    ("WORKER_WAGE", "WORKER_WAGE"),
                    ("WORKER_ADVANCE", "WORKER_ADVANCE"),
                    ("ADVANCE_REPAYMENT", "ADVANCE_REPAYMENT"),
                    ("CAPITAL_INJECTION_ISSUANCE", "CAPITAL_INJECTION_ISSUANCE"),
                    ("CAPITAL_INJECTION_PAYMENT", "CAPITAL_INJECTION_PAYMENT"),
                    ("CAPITAL_WITHDRAWAL_ISSUANCE", "CAPITAL_WITHDRAWAL_ISSUANCE"),
                    ("CAPITAL_WITHDRAWAL_PAYMENT", "CAPITAL_WITHDRAWAL_PAYMENT"),
                    ("CAPITAL_GAIN_ISSUANCE", "CAPITAL_GAIN_ISSUANCE"),
                    ("CAPITAL_LOSS_ISSUANCE", "CAPITAL_LOSS_ISSUANCE"),
                    ("LOSS_COVERAGE_ISSUANCE", "LOSS_COVERAGE_ISSUANCE"),
                    ("LOSS_COVERAGE_PAYMENT", "LOSS_COVERAGE_PAYMENT"),
                    ("PROFIT_DISTRIBUTION_ISSUANCE", "PROFIT_DISTRIBUTION_ISSUANCE"),
                    ("PROFIT_DISTRIBUTION_PAYMENT", "PROFIT_DISTRIBUTION_PAYMENT"),
                    ("PROJECT_FUNDING_ISSUANCE", "PROJECT_FUNDING_ISSUANCE"),
                    ("PROJECT_FUNDING_PAYMENT", "PROJECT_FUNDING_PAYMENT"),
                    ("PROJECT_REFUND_ISSUANC", "PROJECT_REFUND_ISSUANC"),
                    ("PROJECT_REFUND_PAYMENT", "PROJECT_REFUND_PAYMENT"),
                    ("LOAN_ISSUANCE", "LOAN_ISSUANCE"),
                    ("LOAN_PAYMENT", "LOAN_PAYMENT"),
                    ("LOAN_REPAYMENT", "LOAN_REPAYMENT"),
                    ("INTERNAL_TRANSFER_ISSUANCE", "INTERNAL_TRANSFER_ISSUANCE"),
                    ("INTERNAL_TRANSFER_PAYMENT", "INTERNAL_TRANSFER_PAYMENT"),
                ],
                max_length=50,
            ),
        ),
    ]
