# Generated by Django 6.0.1 on 2026-04-16 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0007_remove_fund_entity"),
        ("app_transaction", "0008_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions_outgoing",
                to="app_entity.entity",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions_incoming",
                to="app_entity.entity",
            ),
        ),
    ]
