# Generated by Django 6.0.1 on 2026-04-14 12:35

import apps.app_base.mixins
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_entity", "0002_remove_entity_can_pay_fund_active"),
        ("app_operation", "0005_distribution_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PUR_RET", "Purchase: Return to Vendor (Credit)"),
                            ("PUR_DISC", "Purchase: Post-Invoice Discount (Credit)"),
                            (
                                "PUR_OVER",
                                "Purchase: Price Overcharge Correction (Credit)",
                            ),
                            ("PUR_SHORT", "Purchase: Quantity Shortage (Credit)"),
                            ("PUR_DAM", "Purchase: Damage Allowance (Credit)"),
                            (
                                "PUR_G_RED",
                                "Purchase: Reduction of the amount of the purchase by a not mentioned cause",
                            ),
                            (
                                "PUR_UNDER",
                                "Purchase: Price Undercharge Correction (Debit)",
                            ),
                            ("PUR_TAX", "Purchase: Tax Undercharge (Debit)"),
                            ("PUR_FREIGHT", "Purchase: Unbilled Freight (Debit)"),
                            (
                                "PUR_G_INC",
                                "Purchase: Increase of the amount of the purchase by a not mentioned cause",
                            ),
                            ("SALE_RET", "Sale: Return from Client (Credit)"),
                            ("SALE_DISC", "Sale: Post-Invoice Discount (Credit)"),
                            ("SALE_OVER", "Sale: Price Overcharge Correction (Credit)"),
                            ("SALE_SHORT", "Sale: Quantity Shortage (Credit)"),
                            ("SALE_DAM", "Sale: Damage Allowance (Credit)"),
                            ("SALE_WRITE", "Sale: Bad Debt Write-off (Credit)"),
                            (
                                "SALE_G_RED",
                                "Sale: Reduction of the amount of the sale by a not mentioned cause",
                            ),
                            (
                                "SALE_UNDER",
                                "Sale: Price Undercharge Correction (Debit)",
                            ),
                            ("SALE_TAX", "Sale: Tax Undercharge (Debit)"),
                            ("SALE_FEE", "Sale: Late Payment Penalty (Debit)"),
                            (
                                "SALE_G_INC",
                                "Sale: Increase of the amount of the sale by a not mentioned cause",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "effect",
                    models.CharField(
                        choices=[
                            ("INCREASE", "Increase Original Amount"),
                            ("DECREASE", "Decrease Original Amount"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField()),
                ("date", models.DateField()),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments_supervised",
                        to="app_entity.entity",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="app_operation.operation",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="app_adjustment.adjustment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                apps.app_base.mixins.ImmutableMixin,
                apps.app_base.mixins.AmountCleanMixin,
                apps.app_base.mixins.OfficerMixin,
                apps.app_base.mixins.LinkedIssuanceTransactionMixin,
                apps.app_base.mixins.HasRelatedTransactions,
                models.Model,
            ),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
