# Generated by Django 6.0.4 on 2026-04-20 17:57

import apps.app_base.mixins
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_inventory", "0001_initial"),
        ("app_operation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PUR_RET", "Purchase: Return to Vendor (Credit)"),
                            ("PUR_DISC", "Purchase: Post-Invoice Discount (Credit)"),
                            (
                                "PUR_OVER",
                                "Purchase: Price Overcharge Correction (Credit)",
                            ),
                            ("PUR_SHORT", "Purchase: Quantity Shortage (Credit)"),
                            ("PUR_DAM", "Purchase: Damage Allowance (Credit)"),
                            (
                                "PUR_G_RED",
                                "Purchase: Reduction of the amount of the purchase by a not mentioned cause",
                            ),
                            (
                                "PUR_UNDER",
                                "Purchase: Price Undercharge Correction (Debit)",
                            ),
                            ("PUR_TAX", "Purchase: Tax Undercharge (Debit)"),
                            ("PUR_FREIGHT", "Purchase: Unbilled Freight (Debit)"),
                            (
                                "PUR_G_INC",
                                "Purchase: Increase of the amount of the purchase by a not mentioned cause",
                            ),
                            ("SALE_RET", "Sale: Return from Client (Credit)"),
                            ("SALE_DISC", "Sale: Post-Invoice Discount (Credit)"),
                            ("SALE_OVER", "Sale: Price Overcharge Correction (Credit)"),
                            ("SALE_SHORT", "Sale: Quantity Shortage (Credit)"),
                            ("SALE_DAM", "Sale: Damage Allowance (Credit)"),
                            ("SALE_WRITE", "Sale: Bad Debt Write-off (Credit)"),
                            (
                                "SALE_G_RED",
                                "Sale: Reduction of the amount of the sale by a not mentioned cause",
                            ),
                            (
                                "SALE_UNDER",
                                "Sale: Price Undercharge Correction (Debit)",
                            ),
                            ("SALE_TAX", "Sale: Tax Undercharge (Debit)"),
                            ("SALE_FEE", "Sale: Late Payment Penalty (Debit)"),
                            (
                                "SALE_G_INC",
                                "Sale: Increase of the amount of the sale by a not mentioned cause",
                            ),
                            (
                                "PUR_ITEM_INC",
                                "Purchase: Invoice Item Correction (Increase)",
                            ),
                            (
                                "PUR_ITEM_DEC",
                                "Purchase: Invoice Item Correction (Decrease)",
                            ),
                            (
                                "SALE_ITEM_INC",
                                "Sale: Invoice Item Correction (Increase)",
                            ),
                            (
                                "SALE_ITEM_DEC",
                                "Sale: Invoice Item Correction (Decrease)",
                            ),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="amount"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                ("date", models.DateField(verbose_name="date")),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments_supervised",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="officer",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="app_operation.operation",
                        verbose_name="operation",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="app_adjustment.adjustment",
                        verbose_name="reversal of",
                    ),
                ),
            ],
            options={
                "verbose_name": "adjustment",
                "verbose_name_plural": "adjustments",
            },
            bases=(
                apps.app_base.mixins.ImmutableMixin,
                apps.app_base.mixins.AmountCleanMixin,
                apps.app_base.mixins.OfficerMixin,
                apps.app_base.mixins.LinkedIssuanceTransactionMixin,
                apps.app_base.mixins.HasRelatedTransactions,
                models.Model,
            ),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItemAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PUR_ITEM_INC", "Purchase Item: Increase"),
                            ("PUR_ITEM_DEC", "Purchase Item: Decrease"),
                            ("SALE_ITEM_INC", "Sale Item: Increase"),
                            ("SALE_ITEM_DEC", "Sale Item: Decrease"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                ("date", models.DateField(verbose_name="date")),
                (
                    "adjustment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_adjustment",
                        to="app_adjustment.adjustment",
                        verbose_name="accounting adjustment",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_adjustments_supervised",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="officer",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_adjustments",
                        to="app_operation.operation",
                        verbose_name="operation",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="app_adjustment.invoiceitemadjustment",
                        verbose_name="reversal of",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice item adjustment",
                "verbose_name_plural": "invoice item adjustments",
            },
            bases=(
                apps.app_base.mixins.ImmutableMixin,
                apps.app_base.mixins.OfficerMixin,
                apps.app_base.mixins.HasRelatedTransactions,
                models.Model,
            ),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItemAdjustmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(default=False, verbose_name="deletable"),
                ),
                (
                    "new_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="new quantity",
                    ),
                ),
                (
                    "new_unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="new unit price",
                    ),
                ),
                (
                    "is_removed",
                    models.BooleanField(default=False, verbose_name="is removed"),
                ),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="app_adjustment.invoiceitemadjustment",
                        verbose_name="item adjustment",
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_adjustment_lines",
                        to="app_inventory.invoiceitem",
                        verbose_name="invoice item",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice item adjustment line",
                "verbose_name_plural": "invoice item adjustment lines",
            },
            bases=(apps.app_base.mixins.ImmutableMixin, models.Model),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
