# Generated by Django 6.0.1 on 2026-05-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_adjustment", "0002_alter_adjustment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitemadjustmentline",
            name="is_removed",
        ),
    ]
