# Generated by Django 6.0.1 on 2026-04-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_adjustment", "0002_alter_adjustment_reason"),
        ("app_entity", "0003_alter_contactinfo_options_alter_entity_options_and_more"),
        ("app_operation", "0009_alter_financialcategory_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adjustment",
            options={
                "verbose_name": "adjustment",
                "verbose_name_plural": "adjustments",
            },
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="amount"
            ),
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="deletable",
            field=models.BooleanField(default=False, verbose_name="deletable"),
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="effect",
            field=models.CharField(
                choices=[
                    ("INCREASE", "Increase Original Amount"),
                    ("DECREASE", "Decrease Original Amount"),
                ],
                max_length=10,
                verbose_name="effect",
            ),
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="officer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustments_supervised",
                to="app_entity.entity",
                verbose_name="officer",
            ),
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustments",
                to="app_operation.operation",
                verbose_name="operation",
            ),
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="reason",
            field=models.TextField(blank=True, verbose_name="reason"),
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_by",
                to="app_adjustment.adjustment",
                verbose_name="reversal of",
            ),
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="type",
            field=models.CharField(
                choices=[
                    ("PUR_RET", "Purchase: Return to Vendor (Credit)"),
                    ("PUR_DISC", "Purchase: Post-Invoice Discount (Credit)"),
                    ("PUR_OVER", "Purchase: Price Overcharge Correction (Credit)"),
                    ("PUR_SHORT", "Purchase: Quantity Shortage (Credit)"),
                    ("PUR_DAM", "Purchase: Damage Allowance (Credit)"),
                    (
                        "PUR_G_RED",
                        "Purchase: Reduction of the amount of the purchase by a not mentioned cause",
                    ),
                    ("PUR_UNDER", "Purchase: Price Undercharge Correction (Debit)"),
                    ("PUR_TAX", "Purchase: Tax Undercharge (Debit)"),
                    ("PUR_FREIGHT", "Purchase: Unbilled Freight (Debit)"),
                    (
                        "PUR_G_INC",
                        "Purchase: Increase of the amount of the purchase by a not mentioned cause",
                    ),
                    ("SALE_RET", "Sale: Return from Client (Credit)"),
                    ("SALE_DISC", "Sale: Post-Invoice Discount (Credit)"),
                    ("SALE_OVER", "Sale: Price Overcharge Correction (Credit)"),
                    ("SALE_SHORT", "Sale: Quantity Shortage (Credit)"),
                    ("SALE_DAM", "Sale: Damage Allowance (Credit)"),
                    ("SALE_WRITE", "Sale: Bad Debt Write-off (Credit)"),
                    (
                        "SALE_G_RED",
                        "Sale: Reduction of the amount of the sale by a not mentioned cause",
                    ),
                    ("SALE_UNDER", "Sale: Price Undercharge Correction (Debit)"),
                    ("SALE_TAX", "Sale: Tax Undercharge (Debit)"),
                    ("SALE_FEE", "Sale: Late Payment Penalty (Debit)"),
                    (
                        "SALE_G_INC",
                        "Sale: Increase of the amount of the sale by a not mentioned cause",
                    ),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
