# Generated by Django 6.0.1 on 2026-04-16 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_adjustment",
            "0003_alter_adjustment_options_alter_adjustment_amount_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="adjustment",
            name="officer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustments_supervised",
                to=settings.AUTH_USER_MODEL,
                verbose_name="officer",
            ),
        ),
    ]
