# Generated by Django 6.0.1 on 2026-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_adjustment", "0004_alter_adjustment_officer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adjustment",
            name="effect",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INCREASE", "Increase Original Amount"),
                    ("DECREASE", "Decrease Original Amount"),
                ],
                max_length=10,
                verbose_name="effect",
            ),
        ),
    ]
