# Generated by Django 6.0.1 on 2026-04-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_adjustment", "0006_invoiceitemadjustment_invoiceitemadjustmentline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adjustment",
            name="effect",
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="type",
            field=models.CharField(
                choices=[
                    ("PUR_RET", "Purchase: Return to Vendor (Credit)"),
                    ("PUR_DISC", "Purchase: Post-Invoice Discount (Credit)"),
                    ("PUR_OVER", "Purchase: Price Overcharge Correction (Credit)"),
                    ("PUR_SHORT", "Purchase: Quantity Shortage (Credit)"),
                    ("PUR_DAM", "Purchase: Damage Allowance (Credit)"),
                    (
                        "PUR_G_RED",
                        "Purchase: Reduction of the amount of the purchase by a not mentioned cause",
                    ),
                    ("PUR_UNDER", "Purchase: Price Undercharge Correction (Debit)"),
                    ("PUR_TAX", "Purchase: Tax Undercharge (Debit)"),
                    ("PUR_FREIGHT", "Purchase: Unbilled Freight (Debit)"),
                    (
                        "PUR_G_INC",
                        "Purchase: Increase of the amount of the purchase by a not mentioned cause",
                    ),
                    ("SALE_RET", "Sale: Return from Client (Credit)"),
                    ("SALE_DISC", "Sale: Post-Invoice Discount (Credit)"),
                    ("SALE_OVER", "Sale: Price Overcharge Correction (Credit)"),
                    ("SALE_SHORT", "Sale: Quantity Shortage (Credit)"),
                    ("SALE_DAM", "Sale: Damage Allowance (Credit)"),
                    ("SALE_WRITE", "Sale: Bad Debt Write-off (Credit)"),
                    (
                        "SALE_G_RED",
                        "Sale: Reduction of the amount of the sale by a not mentioned cause",
                    ),
                    ("SALE_UNDER", "Sale: Price Undercharge Correction (Debit)"),
                    ("SALE_TAX", "Sale: Tax Undercharge (Debit)"),
                    ("SALE_FEE", "Sale: Late Payment Penalty (Debit)"),
                    (
                        "SALE_G_INC",
                        "Sale: Increase of the amount of the sale by a not mentioned cause",
                    ),
                    ("PUR_ITEM_INC", "Purchase: Invoice Item Correction (Increase)"),
                    ("PUR_ITEM_DEC", "Purchase: Invoice Item Correction (Decrease)"),
                    ("SALE_ITEM_INC", "Sale: Invoice Item Correction (Increase)"),
                    ("SALE_ITEM_DEC", "Sale: Invoice Item Correction (Decrease)"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
