# Generated by Django 6.0.1 on 2026-03-13 16:41

import apps.app_base.mixins
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_entity", "0012_auto_20260303_1436"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deletable", models.BooleanField(default=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("CASH_INJECTION", "Cash Injection"),
                            ("CASH_WITHDRAWAL", "Cash Withdrawal"),
                            ("PROJECT_FUNDING", "Project Funding"),
                            ("PROJECT_REFUND", "Project Refund"),
                            ("PROFIT_DISTRIBUTION", "Profit Distribution"),
                            ("LOSS_COVERAGE", "Loss Coverage"),
                            ("INTERNAL_TRANSFER", "Internal Transfer"),
                            ("DEBT_ISSUANCE", "Debt Issuance"),
                            ("DEBT_PAYMENT", "Debt Payment"),
                            ("DEBT_REPAYMENT", "Debt Repayment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_injections_incoming",
                        to="app_entity.entity",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_injections_supervised",
                        to="app_entity.entity",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="app_personal_operation.operation",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_injections_outgoing",
                        to="app_entity.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Injection",
                "verbose_name_plural": "Cash Injections",
                "ordering": ["-date", "-created_at"],
            },
            bases=(
                apps.app_base.mixins.ImmutableMixin,
                apps.app_base.mixins.AdjustableMixin,
                apps.app_base.mixins.AmountCleanMixin,
                apps.app_base.mixins.HasLinkedTransactionMixin,
                apps.app_base.mixins.Has2FundsMixin,
                apps.app_base.mixins.HasRelatedTransactions,
                models.Model,
            ),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
