# Generated by Django 6.0.1 on 2026-03-14 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_entity", "0012_auto_20260303_1436"),
        ("app_personal_operation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operation",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Operation",
                "verbose_name_plural": "Operations",
            },
        ),
        migrations.AlterField(
            model_name="operation",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations_incoming",
                to="app_entity.entity",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="officer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations_supervised",
                to="app_entity.entity",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("CASH_INJECTION", "Cash Injection"),
                    ("CASH_WITHDRAWAL", "Cash Withdrawal"),
                    ("PROJECT_FUNDING", "Project Funding"),
                    ("PROJECT_REFUND", "Project Refund"),
                    ("PROFIT_DISTRIBUTION", "Profit Distribution"),
                    ("LOSS_COVERAGE", "Loss Coverage"),
                    ("INTERNAL_TRANSFER", "Internal Transfer"),
                    ("LOAN_ISSUANCE", "Loan Issuance"),
                    ("LOAN_PAYMENT", "Loan Payment"),
                    ("LOAN_REPAYMENT", "Loan Repayment"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations_outgoing",
                to="app_entity.entity",
            ),
        ),
    ]
