from django.urls import path

from . import views

urlpatterns = [
    path(
        "periods/<int:entity_pk>/",
        views.period_list_view,
        name="period_list_view",
    ),
    path(
        "periods/<int:period_pk>/detail/",
        views.period_detail_view,
        name="period_detail_view",
    ),
    path(
        "periods/<int:period_pk>/close/",
        views.period_close_view,
        name="period_close_view",
    ),
    path(
        "periods/<int:period_pk>/ledger/",
        views.period_ledger_view,
        name="period_ledger_view",
    ),
    path(
        "<int:person_pk>/list/",
        views.operation_list_view,
        name="operation_list_view",
    ),
    path(
        "<int:pk>/evaluate/<int:product_pk>/",
        views.EvaluationCreateView.as_view(),
        name="evaluation_create_view",
    ),
    path(
        "<int:pk>/birth/create",
        views.BirthCreateView.as_view(),
        name="birth_create_view",
    ),
    path(
        "<int:pk>/death/create",
        views.DeathCreateView.as_view(),
        name="death_create_view",
    ),
    # path(
    #     "<int:pk>/purchase/create",
    #     views.PurchaseCreateView.as_view(),
    #     name="purchase_create_view",
    # ),
    # Just for testing
    path(
        "<int:pk>/purchase/wizard/",
        views.purchase_wizard_view,
        name="purchase_wizard_step1",
    ),
    path(
        "<int:pk>/purchase/wizard/cancel/",
        views.cancel_purchase_wizard_view,
        name="purchase_wizard_cancel",
    ),
    path(
        "<int:pk>/purchase/wizard/<int:step>/",
        views.purchase_wizard_view,
        name="purchase_wizard_step_new",
    ),
    path(
        "<int:pk>/purchase/invoice/",
        views.purchase_invoice_view,
        name="purchase_invoice",
    ),
    path(
        "<int:pk>/purchase/invoice/select-template/",
        views.purchase_select_template_view,
        name="purchase_select_template",
    ),
    path(
        "<int:pk>/purchase/invoice/add-item/",
        views.purchase_add_item_view,
        name="purchase_add_item",
    ),
    path(
        "<int:pk>/purchase/invoice/add-item/<int:idx>/",
        views.purchase_add_item_view,
        name="purchase_edit_item",
    ),
    path(
        "<int:pk>/purchase/invoice/delete-item/<int:idx>/",
        views.purchase_delete_item_view,
        name="purchase_delete_item",
    ),
    path(
        "<int:pk>/purchase/invoice/submit/",
        views.purchase_submit_view,
        name="purchase_submit",
    ),
    path(
        "<int:pk>/sale/wizard/",
        views.sale_wizard_view,
        name="sale_wizard_step1",
    ),
    path(
        "<int:pk>/sale/wizard/cancel/",
        views.cancel_sale_wizard_view,
        name="sale_wizard_cancel",
    ),
    path(
        "<int:pk>/sale/wizard/<int:step>/",
        views.sale_wizard_view,
        name="sale_wizard_step_new",
    ),
    path(
        "<int:pk>/sale/invoice/",
        views.sale_invoice_view,
        name="sale_invoice",
    ),
    path(
        "<int:pk>/sale/invoice/select-template/",
        views.sale_select_template_view,
        name="sale_select_template",
    ),
    path(
        "<int:pk>/sale/invoice/add-item/",
        views.sale_add_item_view,
        name="sale_add_item",
    ),
    path(
        "<int:pk>/sale/invoice/add-item/<int:idx>/",
        views.sale_add_item_view,
        name="sale_edit_item",
    ),
    path(
        "<int:pk>/sale/invoice/delete-item/<int:idx>/",
        views.sale_delete_item_view,
        name="sale_delete_item",
    ),
    path(
        "<int:pk>/sale/invoice/submit/",
        views.sale_submit_view,
        name="sale_submit",
    ),
    path(
        "<int:pk>/sale/create",
        views.SaleCreateView.as_view(),
        name="sale_create_view",
    ),
    path(
        "<int:pk>/<op_type>/create",
        views.OperationCreateView.as_view(),
        name="operation_create_view",
    ),
    path(
        "repayment/<int:pk>/create",
        views.record_transaction_repayment,
        name="record_transaction_repayment",
    ),
    path(
        "payment/<int:pk>/create",
        views.record_transaction_payment,
        name="record_transaction_payment",
    ),
    path(
        "<int:pk>/adjustment/create",
        views.record_accounting_adjustment,
        name="record_accounting_adjustment",
    ),
    path(
        "<int:pk>/adjustment/items/create",
        views.record_item_adjustment,
        name="record_item_adjustment",
    ),
    path(
        "adjustment/<int:adjustment_id>/reverse/",
        views.reverse_adjustment,
        name="reverse_adjustment",
    ),
    path(
        "adjustment/item/<int:item_adjustment_id>/reverse/",
        views.reverse_item_adjustment,
        name="reverse_item_adjustment",
    ),
    path(
        "<int:pk>/detail/",
        views.operation_detail_view,
        name="operation_detail_view",
    ),
    path(
        "<int:pk>/reverse/",
        views.operation_reverse_view,
        name="operation_reverse_view",
    ),
    path(
        "<int:pk>/edit/",
        views.operation_update_view,
        name="operation_update_view",
    ),
]
